[package]
name = "backend-shared"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
base64 = "0.21"
chrono = { version = "0.4", features = [ "serde" ] }
dotenv = "0.15"
env_logger = "0.10"
futures = "0.3"
itertools = "0.10"
log = "0.4"
rust_decimal = "1.29"
sea-orm = { version = "0.11.2", features = [ "macros" ] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strum = "0.24"
strum_macros = "0.24"
thiserror = "1.0"
tokio = { version = "1.27", features = ["rt", "macros"] }
uuid = { version = "1.3", features = ["serde", "v4"] }

[dev-dependencies]
backend-test = { path = "../backend-test" }
sea-orm = { version = "0.11.2", features = [ "sqlx-sqlite", "runtime-tokio-rustls", "macros" ] }
