[package]
name = "backend-shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.24"
log = "0.4.17"
env_logger = "0.9.0"
anyhow = "1.0.62"
tokio = { version = "1.20.1", features = ["rt", "macros"] }
sea-orm = { version = "0.9.2", features = [ "macros" ] }
serde = "1.0.144"
serde_json = "1.0.85"

[dev-dependencies]
sea-orm = { version = "0.9.2", features = [ "sqlx-sqlite", "runtime-tokio-rustls", "macros" ] }
