[package]
name = "migration"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0"
backend-shared = { path = "../backend-shared" }
chrono = { version = "0.4", features = [ "serde" ] }
dotenv = "0.15"
env_logger = "0.10"

fake = { version = "2.6", features = ['chrono', 'rust_decimal'] }
log = "0.4"
rand = "0.8"
rust_decimal = "1.29"
tokio = { version = "1.27", features = ["rt", "macros"] }
uuid = { version = "1.3", features = ["serde", "v4"] }

[dependencies.sea-orm-migration]
version = "0.11.2"
features = ["sqlx-sqlite", "runtime-tokio-rustls"]

[dev-dependencies]
tokio = { version = "1.27", features = ["rt", "macros"] }
