[package]
name = "test-suite"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
backend-core = { path = "../backend-core" }
chrono = { version = "0.4", features = [ "serde" ] }
dotenv = "0.15"
env_logger = "0.11"
fake = { version = "2.9", features = ["bigdecimal", "chrono"] }
futures = "0.3"
itertools = "0.13"
log = "0.4"
migration = { path = "../migration" }
rand = "0.8"
rust_decimal = "1.35"
tokio = { version = "1.37", features = ["rt", "macros"] }
uuid = { version = "1.8", features = ["serde", "v4", "macro-diagnostics"] }
