[package]
name = "backend-test"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-trait = "0.1"
backend-shared = { path = "../backend-shared" }
chrono = { version = "0.4", features = [ "serde" ] }
dotenv = "0.15"
env_logger = "0.10"
fake = { version = "2.5", features = ['chrono', 'uuid', 'rust_decimal'] }
itertools = "0.10"
lazy_static = "1.4"
log = "0.4"
migration = { path = "../migration" }
rand = "0.8"
rust_decimal = "1.29"
tokio = { version = "1.26", features = ["rt", "macros"] }
uuid = { version = "1.3", features = ["serde", "v4"] }

[dependencies.sea-orm-migration]
version = "0.11"
features = ["sqlx-sqlite", "runtime-tokio-rustls"]
