[package]
name = "endpoint-graphql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
backend-shared = { path = "../backend-shared" }
log = "0.4.17"
env_logger = "0.9.0"
anyhow = "1.0.63"
tokio = { version = "1.20.1", features = ["rt", "macros"] }
sea-orm = { version = "0.9.2", features = [ "sqlx-postgres", "runtime-tokio-rustls", "macros" ] }
