[package]
name = "endpoint-graphql"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
backend-shared = { path = "../backend-shared" }
dotenv = "0.15"
env_logger = "0.10"
log = "0.4"
sea-orm = { version = "0.10", features = [ "sqlx-postgres", "runtime-tokio-rustls", "macros" ] }
tokio = { version = "1.24", features = ["rt", "macros"] }
